### PR TITLE
New website design

### PR DESCRIPTION
**Pull request by Ajiva-D**

### CODE REVIEW

**Comment by RedVeil** [comment]
The "Connect your Wallet" button is missing here.
image

**Comment by RedVeil** [comment]
@anthonymartin We need some copy here.
image

**Comment by RedVeil** [comment]
Can we mid align this dropdown icon?
image

**Comment by RedVeil** [comment]
Besides that its looking good but we need to hook it up to correct data for TVL, APY and add proper links

**Comment by RedVeil** [comment]
On mobile the "Connect Wallet"-Button is missing here:
image

**Comment by Ajiva-D** [comment]
> The "Connect your Wallet" button is missing here. image

It's not missing actually, it just hides when the user connects or is already connected

**Comment by Ajiva-D** [comment]
> @anthonymartin We need some copy here. image

Copy was provided, and will be updated in a different pr

**Comment by Ajiva-D** [comment]
> On mobile the "Connect Wallet"-Button is missing here: image

Same thing with the one on desktop, it just hides when already connected

**Comment by RedVeil** [comment]
@Ajiva-D The Mobile view is scrollable to the side. Could you take a look at this? Maybe we need to set the width better or hide overflow

**Comment by RedVeil** [comment]
Closed since new changes are in https://github.com/popcorndao/sweet-caramel/pull/1147

**Pull request closed without merging**
