### PR TITLE
Feature/tvl card

### PR DESCRIPTION
**Pull request by K-G-J**
- new TVL card for popcorn.finance landing page 
- code in [/packages/app/components/TVLCard.tsx ](https://github.com/popcorndao/sweet-caramel/blob/feature/tvl-card/packages/app/components/TVLCard.tsx)

### CODE REVIEW

**Comment by anthonymartin** [comment]
@K-G-J can you take a look and see if this is already in the new site w/ rebrand? if not could you move the logic over there and we can ignore this one for the old site

**Comment by K-G-J** [comment]
There are tvl cards for the [staking page](https://www.popcorndao.finance/ethereum/staking) but I don't see a tvl or mynetworth card on the new site landing page

**Comment by anthonymartin** [comment]
can you make sure the logic is correct on the rebranded site?

**Comment by K-G-J** [comment]
yes will look into it

**Pull request closed without merging**
