### PR TITLE
New staking page

### PR DESCRIPTION
**Pull request by Ajiva-D**

### CODE REVIEW

**Comment by RedVeil** [comment]
Could we center theses icons? 
image

**Comment by RedVeil** [comment]
Token Emission is in normal case in figma.
image

**Comment by RedVeil** [comment]
Could you rename this to "view" ? 
image

**Comment by RedVeil** [comment]
This image should be full width.
image

**Comment by Ajiva-D** [comment]
> Could we center theses icons? image

I don't know why these look off for you, cos it's actually centralised, maybe try a different browser and see if it's the same so we can pinpoint the problem

**Review by RedVeil — APPROVED** [review]

**Pull request merged**
