### PR TITLE
New 3x/butter page

### PR DESCRIPTION
**Pull request by Ajiva-D**

### CODE REVIEW

**Comment by RedVeil** [comment]
Could we center these icons? 
image

It looks okish for USDC but especially 3X becomes a bit strange. (This is also the case on desktop)

**Comment by RedVeil** [comment]
Redeem has a weird display issue on desktop:
image

**Comment by RedVeil** [comment]
For some reason the image doesnt cover the full width:
image

**Comment by RedVeil** [comment]
Nothing is displayed when i have no batches. I think we should atleast show some placeholder
image

**Comment by RedVeil** [comment]
The Tab symbols are inverted. Instead of the active tab beeing white and the rest having lower opacity the active one has lower opacity.
image

**Comment by RedVeil** [comment]
Step 3 is smaller than the other two:
image

**Comment by RedVeil** [comment]
The Disconnect Button of the Navbar is a bit wider than the content of the page. Is that intended?
image

**Comment by Ajiva-D** [comment]
> Step 3 is smaller than the other two: image

Do you mean the content?

**Comment by RedVeil** [comment]
Even though its not explicitly mentioned in the figma design i think the batches should align the with mintInterface on the side. If someone has more than these batches they should become scrollable.

**Comment by RedVeil** [comment]
> > Step 3 is smaller than the other two: image
> 
> Do you mean the content?

The whole card is smaller. So there is more space all of a sudden between it and the batchProgress below. I think the card size shouldnt change. Just means that the info text in the tutorial will have more space around it.

**Review by RedVeil — APPROVED** [review]

**Pull request merged**
